name: ${name}
version: ${version}
description: Permissions module for vane

authors:
  - oddlama
website: 'https://github.com/oddlama/vane'

main: org.oddlama.vane.permissions.Permissions

api-version: '1.21'

dependencies:
  server:
    vane-core:
      required: true
      load: BEFORE